In [1]:
import numpy as np
import pandas as pd


In [2]:
#creating a dataframe
cars_train = pd.read_csv("cars_train.csv")
cars_test = pd.read_csv("cars_test.csv")

In [3]:
print(cars_train.shape)
cars_train.head()

(1381, 7)


vhigh   high      3  more  small   low  unacc
0   low  vhigh      3     4  small   med  unacc
1   low   high  5more  more    big   low  unacc
2  high    med      4     2  small   med  unacc
3   low    low      3  more    big   med   good
4   low    low      2     4    big  high  vgood

In [4]:
print(cars_test.shape)
cars_test.head()

(345, 7)


med  vhigh 5more     4  small   low  unacc
0  vhigh   high     2     2    big   med  unacc
1    low   high     2  more  small   low  unacc
2  vhigh  vhigh     3     2    big  high  unacc
3    low    med     4     4    med   med   good
4  vhigh    low     3  more    med   low  unacc

In [5]:
cars_train.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [6]:
cars_train.head()

buying  maint  doors persons lug_boot safety classes
0    low  vhigh      3       4    small    med   unacc
1    low   high  5more    more      big    low   unacc
2   high    med      4       2    small    med   unacc
3    low    low      3    more      big    med    good
4    low    low      2       4      big   high   vgood

In [7]:
cars_test.head()

buying  maint doors persons lug_boot safety classes
0  vhigh   high     2       2      big    med   unacc
1    low   high     2    more    small    low   unacc
2  vhigh  vhigh     3       2      big   high   unacc
3    low    med     4       4      med    med    good
4  vhigh    low     3    more      med    low   unacc

In [8]:
cars_train.describe()

buying  maint  doors persons lug_boot safety classes
count    1381   1381   1381    1381     1381   1381    1381
unique      4      4      4       3        3      3       4
top      high  vhigh  5more    more      big   high   unacc
freq      349    352    349     465      467    463     958

In [9]:
cars_test.describe()

buying maint doors persons lug_boot safety classes
count     345   345   345     345      345    345     345
unique      4     4     4       3        3      3       4
top       low   low     2       2      med    low   unacc
freq       94    94    92     122      122    117     250

In [10]:
cars_train.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [11]:
cars_test.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [12]:
cars_test.drop("classes",axis=1,inplace=True)
cars_test.head()

buying  maint doors persons lug_boot safety
0  vhigh   high     2       2      big    med
1    low   high     2    more    small    low
2  vhigh  vhigh     3       2      big   high
3    low    med     4       4      med    med
4  vhigh    low     3    more      med    low

In [13]:
cars_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 0 to 344
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    345 non-null    object
 1   maint     345 non-null    object
 2   doors     345 non-null    object
 3   persons   345 non-null    object
 4   lug_boot  345 non-null    object
 5   safety    345 non-null    object
dtypes: object(6)
memory usage: 16.3+ KB


In [14]:
#transforming Categorical data to Numerical
from sklearn.preprocessing import LabelEncoder

colname=['buying','maint','doors','persons','lug_boot','safety','classes']

le=LabelEncoder()

for x in colname:
    cars_train[x]=le.fit_transform(cars_train[x])
    

#in     

In [15]:
cars_train.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       1      3      1        1         2       2        2
1       1      0      3        2         0       1        2
2       0      2      2        0         2       2        2
3       1      1      1        2         0       2        1
4       1      1      0        1         0       0        3

In [16]:
#transforming Categorical data to Numerical
from sklearn.preprocessing import LabelEncoder

colname=['buying','maint','doors','persons','lug_boot','safety']

le=LabelEncoder()

for x in colname:
    cars_test[x]=le.fit_transform(cars_test[x])

In [17]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       3      0      0        0         0       2
1       1      0      0        2         2       1
2       3      3      1        0         0       0
3       1      2      2        1         1       2
4       3      1      1        2         1       1

In [18]:
X=cars_train.values[:,0:-1]
Y=cars_train.values[:,-1]
Y=Y.astype(int)

In [19]:
X.shape

(1381, 6)

In [20]:
Y.shape

(1381,)

In [21]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)
X = scaler.transform(X)

In [22]:
print(X)

[[-0.44676413  1.326301   -0.45702222 -0.0097647   1.22676414  1.22430616]
 [-0.44676413 -1.35020414  1.33346768  1.21614869 -1.21439044  0.00177051]
 [-1.33835556  0.43413262  0.43822273 -1.23567808  1.22676414  1.22430616]
 ...
 [-1.33835556  1.326301    1.33346768 -0.0097647   0.00618685 -1.22076515]
 [ 0.44482729  0.43413262  0.43822273 -0.0097647  -1.21439044  0.00177051]
 [ 0.44482729 -0.45803576  1.33346768  1.21614869  1.22676414 -1.22076515]]


In [23]:
from sklearn.model_selection import train_test_split  #<1000=in range of 80-20  &  >1000=in range of 70-80

#Split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [24]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1104, 6)
(1104,)
(277, 6)
(277,)


In [25]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree = DecisionTreeClassifier(criterion="gini",random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)

Y_pred = model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[ 65   1   1   0]
 [  0  11   2   0]
 [  2   0 188   0]
 [  0   0   0   7]]
Classification report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        67
           1       0.92      0.85      0.88        13
           2       0.98      0.99      0.99       190
           3       1.00      1.00      1.00         7

    accuracy                           0.98       277
   macro avg       0.97      0.95      0.96       277
weighted avg       0.98      0.98      0.98       277

Accuracy of the model:  0.9783393501805054


In [27]:
model_DecisionTree.score(X_train,Y_train)

1.0

In [28]:
print(list(zip(cars_train.columns[0:-1],model_DecisionTree.feature_importances_)))

[('buying', 0.1395650486206521), ('maint', 0.2681233738445883), ('doors', 0.03998978881958271), ('persons', 0.1997476010139279), ('lug_boot', 0.10560315427755128), ('safety', 0.24697103342369772)]


In [29]:
from sklearn import tree
with open(r"model_DecisionTree.txt", "w") as f:
    
    f = tree.export_graphviz(model_DecisionTree, feature_names=cars_train.columns[0:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree

In [30]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree = DecisionTreeClassifier(criterion="gini",random_state=10,
                                           splitter="best",min_samples_leaf=5,
                                           max_depth=10,max_leaf_nodes=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)

Y_pred = model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[ 52   0  15   0]
 [ 13   0   0   0]
 [ 11   0 179   0]
 [  7   0   0   0]]
Classification report:
              precision    recall  f1-score   support

           0       0.63      0.78      0.69        67
           1       0.00      0.00      0.00        13
           2       0.92      0.94      0.93       190
           3       0.00      0.00      0.00         7

    accuracy                           0.83       277
   macro avg       0.39      0.43      0.41       277
weighted avg       0.78      0.83      0.81       277

Accuracy of the model:  0.8339350180505415


C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
model_DecisionTree.score(X_train,Y_train)

0.8523550724637681

In [33]:
from sklearn import tree
with open(r"model_DecisionTree.txt", "w") as f:
    
    f = tree.export_graphviz(model_DecisionTree, feature_names=cars_train.columns[0:-1],
                             out_file=f)
    
#generate the file and upload theFsta code in webgraphviz.com to plot the decision tree

In [34]:
from sklearn.svm import SVC
svc_model=SVC(kernel='rbf',C=1,gamma=0.1)
svc_model.fit(X_train,Y_train)
Y_pred=svc_model.predict(X_test)
print(list(Y_pred))

[2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 3, 2, 0, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 3, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 3, 2, 0, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2]


In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[ 52   0  15   0]
 [ 13   0   0   0]
 [ 10   0 180   0]
 [  2   0   0   5]]
Classification report:
              precision    recall  f1-score   support

           0       0.68      0.78      0.72        67
           1       0.00      0.00      0.00        13
           2       0.92      0.95      0.94       190
           3       1.00      0.71      0.83         7

    accuracy                           0.86       277
   macro avg       0.65      0.61      0.62       277
weighted avg       0.82      0.86      0.84       277

Accuracy of the model:  0.855595667870036


C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
from sklearn.svm import SVC
svc_model=SVC(kernel='rbf',C=90,gamma=0.1)
svc_model.fit(X_train,Y_train)
Y_pred=svc_model.predict(X_test)
print(list(Y_pred))

[2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 3, 2, 2, 1, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 3, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 1, 2, 2, 1, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 3, 2, 2, 2, 0, 0, 0, 1, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 3, 1, 0, 0, 2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2]


In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[ 65   1   1   0]
 [  0  13   0   0]
 [  0   0 190   0]
 [  0   0   0   7]]
Classification report:
              precision    recall  f1-score   support

           0       1.00      0.97      0.98        67
           1       0.93      1.00      0.96        13
           2       0.99      1.00      1.00       190
           3       1.00      1.00      1.00         7

    accuracy                           0.99       277
   macro avg       0.98      0.99      0.99       277
weighted avg       0.99      0.99      0.99       277

Accuracy of the model:  0.9927797833935018


In [38]:
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=33,
                              metric='euclidean')

#euclidean,manhattan,minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (0, 2), (0, 2), (2, 2), (3, 3), (2, 2), (2, 2), (1, 0), (2, 2), (2, 2), (0, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 2), (0, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (3, 3), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (1, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (1, 2), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (1, 0), (3, 0), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (0, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 2), (0, 2), (2, 2), (2, 2), (0, 2), (2, 2), (0, 0), (2, 2),

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[ 30   0  37   0]
 [  8   0   5   0]
 [  2   0 188   0]
 [  1   0   1   5]]
Classification report:
              precision    recall  f1-score   support

           0       0.73      0.45      0.56        67
           1       0.00      0.00      0.00        13
           2       0.81      0.99      0.89       190
           3       1.00      0.71      0.83         7

    accuracy                           0.81       277
   macro avg       0.64      0.54      0.57       277
weighted avg       0.76      0.81      0.77       277

Accuracy of the model:  0.8050541516245487


C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [40]:
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=5,
                              metric='euclidean')

#euclidean,manhattan,minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(2, 2), (2, 2), (2, 0), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (3, 3), (2, 2), (2, 2), (1, 1), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 3), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (0, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (2, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (1, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 0), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (1, 0), (3, 3), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2),

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[ 60   0   6   1]
 [  7   6   0   0]
 [  6   0 184   0]
 [  0   0   1   6]]
Classification report:
              precision    recall  f1-score   support

           0       0.82      0.90      0.86        67
           1       1.00      0.46      0.63        13
           2       0.96      0.97      0.97       190
           3       0.86      0.86      0.86         7

    accuracy                           0.92       277
   macro avg       0.91      0.80      0.83       277
weighted avg       0.93      0.92      0.92       277

Accuracy of the model:  0.924187725631769


In [42]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier = LogisticRegression()

#train the model object
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(Y_pred)
print(list(zip(Y_test,Y_pred)))

[2 2 0 2 2 0 2 3 0 2 0 2 2 0 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2
 2 2 2 0 2 0 2 2 0 2 2 2 2 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2
 2 0 2 0 2 2 2 2 2 2 2 0 2 2 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 2 0 2 2
 2 2 3 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 0 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 2 2 2 2 2 0 2 2 2 0 2 0 2 2 2 2 2 2 2 2
 2 2 2 2 2 3 0 2 2 2 0 2 2 2 2 2 2 2 2 3 2 2 2 0 2 2 0 2 2 2 2 2 2 2 0 2 2
 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2 0 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 3 0 2 0 2 2 2 0 2 2 2]
[(2, 2), (2, 2), (2, 0), (2, 2), (0, 2), (2, 0), (2, 2), (0, 3), (0, 0), (2, 2), (3, 0), (2, 2), (2, 2), (1, 0), (2, 2), (2, 2), (0, 2), (0, 2), (2, 2), (0, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (0, 2), (2, 2), (2, 2), (0, 2), (0, 2), (0, 2), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (0, 2), (2, 0), (2, 2), (2, 0), (2, 2), (2, 2), (2, 0), (0, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (3, 

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[ 11   0  52   4]
 [  4   0   9   0]
 [ 24   0 166   0]
 [  4   0   2   1]]
Classification report:
              precision    recall  f1-score   support

           0       0.26      0.16      0.20        67
           1       0.00      0.00      0.00        13
           2       0.72      0.87      0.79       190
           3       0.20      0.14      0.17         7

    accuracy                           0.64       277
   macro avg       0.30      0.30      0.29       277
weighted avg       0.56      0.64      0.60       277

Accuracy of the model:  0.6425992779783394


C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nilima\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Base model is simpler than the tuned model.


# test data

In [44]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       3      0      0        0         0       2
1       1      0      0        2         2       1
2       3      3      1        0         0       0
3       1      2      2        1         1       2
4       3      1      1        2         1       1

In [45]:
test=cars_test.values
test=scaler.transform(test)
#print(test)

#fit only on the train data
#transform on both the train as well as test data

In [46]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree = DecisionTreeClassifier(criterion="gini",random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)



DecisionTreeClassifier(random_state=10)

In [47]:
test_pred = model_DecisionTree.predict(test)
test_pred


array([2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3, 2,
       0, 2, 0, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 3, 2, 2, 0,
       0, 2, 2, 3, 2, 2, 2, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2,
       2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 3, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 0, 3, 0, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 3, 0, 2, 2, 2, 3, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0, 2,
       0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2,
       2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0, 2, 0, 3, 3, 0, 2, 0,
       2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2,

In [49]:
cars_test = pd.read_csv(r'C:\Users\GM\Downloads\drive-download-20230308T161730Z-001\cars_test.csv',header=None)
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test["Pred"]=test_pred
cars_test["Pred"]=cars_test["Pred"].map({0:"acc",1:"good",2:"unacc",3:"vgood"})
cars_test.head()

ValueError: Length of values (345) does not match length of index (346)

In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(cars_test.classes,cars_test.Pred)
print(cfm)

print("Classification report:")

print(classification_report(cars_test.classes,cars_test.Pred))

acc=accuracy_score(cars_test.classes,cars_test.Pred)
print("Accuracy of the model: ",acc)

AttributeError: 'DataFrame' object has no attribute 'Pred'

In [ ]:
#cars_test.to_excel("Decision Test Output.xlxs",header=True)
#Saving the data

# Random Forest

In [51]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest = RandomForestClassifier(n_estimators=100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred = model_RandomForest.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[ 63   0   3   1]
 [  2  11   0   0]
 [  4   0 186   0]
 [  0   0   0   7]]
Classification report:
              precision    recall  f1-score   support

           0       0.91      0.94      0.93        67
           1       1.00      0.85      0.92        13
           2       0.98      0.98      0.98       190
           3       0.88      1.00      0.93         7

    accuracy                           0.96       277
   macro avg       0.94      0.94      0.94       277
weighted avg       0.96      0.96      0.96       277

Accuracy of the model:  0.9638989169675091


In [ ]:
NAME=input("ENTER NAME")
number =input("ENTER PHONE NUMBER")
email=input("ENTER EMAIL")